version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nxhOBU4pVm9p2B1
      MYSQL_DATABASE: lemon_db
      MYSQL_USER: lemon
      MYSQL_PASSWORD: nxhOBU4pVm9p2B1
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
